spring.application.name=HovedOpgave_JonasJakobsen
spring.jpa.hibernate.ddl-auto=create-only
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASSWORD}

